"""add scalable polling state

Revision ID: 5a20f2a5979e
Revises: 3cee144a14b8
Create Date: 2026-07-21 13:58:30.194338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a20f2a5979e'
down_revision: Union[str, Sequence[str], None] = '3cee144a14b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_poll_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('poll_lease_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('poll_lease_owner', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_poll_started_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_poll_finished_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_error_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('poll_duration_ms', sa.Integer(), nullable=True))
        batch_op.create_index('ix_routers_poll_due', ['is_active', 'next_poll_at', 'poll_lease_until'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routers', schema=None) as batch_op:
        batch_op.drop_index('ix_routers_poll_due')
        batch_op.drop_column('poll_duration_ms')
        batch_op.drop_column('last_error_code')
        batch_op.drop_column('consecutive_failures')
        batch_op.drop_column('last_poll_finished_at')
        batch_op.drop_column('last_poll_started_at')
        batch_op.drop_column('poll_lease_owner')
        batch_op.drop_column('poll_lease_until')
        batch_op.drop_column('next_poll_at')

    # ### end Alembic commands ###
